from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from datetime import datetime
import os


def generate_pdf(prediction, confidence, original_image_path, heatmap_path):
    """
    Generate professional LungAI PDF report.
    """

    output_folder = "uploads"
    os.makedirs(output_folder, exist_ok=True)

    pdf_path = os.path.join(output_folder, "LungAI_Report.pdf")

    c = canvas.Canvas(pdf_path, pagesize=A4)

    width, height = A4

    # ==================================================
    # Header
    # ==================================================

    c.setFillColor(HexColor("#1565C0"))
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(width / 2, height - 45, "LungAI")

    c.setFillColor(HexColor("#333333"))
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(
        width / 2,
        height - 70,
        "AI Lung Disease Detection Report"
    )

    c.setStrokeColor(HexColor("#1565C0"))
    c.setLineWidth(2)
    c.line(40, height - 85, width - 40, height - 85)

    # ==================================================
    # Patient Information
    # ==================================================

    c.setStrokeColor(HexColor("#1565C0"))
    c.roundRect(
        40,
        height - 190,
        width - 80,
        85,
        10
    )

    c.setFillColor(HexColor("#1565C0"))
    c.setFont("Helvetica-Bold", 15)
    c.drawString(55, height - 125, "Patient Information")

    c.setFillColor(HexColor("#000000"))
    c.setFont("Helvetica", 11)

    c.drawString(60, height - 145, "Report ID : LUNG-0001")
    c.drawString(
        240,
        height - 145,
        f"Date : {datetime.now().strftime('%d-%m-%Y')}"
    )

    c.drawString(
        420,
        height - 145,
        f"Time : {datetime.now().strftime('%H:%M')}"
    )

    c.drawString(60, height - 165, "Generated By : LungAI")

    # ==================================================
    # AI Diagnosis
    # ==================================================

    c.setStrokeColor(HexColor("#2E7D32"))
    c.roundRect(
        40,
        height - 300,
        width - 80,
        90,
        10
    )

    c.setFillColor(HexColor("#2E7D32"))
    c.setFont("Helvetica-Bold", 15)
    c.drawString(55, height - 230, "AI Diagnosis")

    c.setFillColor(HexColor("#000000"))
    c.setFont("Helvetica-Bold", 13)

    c.drawString(60, height - 250, f"Disease : {prediction}")
    c.drawString(60, height - 270, f"Confidence : {confidence}%")

    if confidence >= 90:
        risk = "HIGH"
    elif confidence >= 70:
        risk = "MEDIUM"
    else:
        risk = "LOW"

    c.drawString(300, height - 250, f"Risk Level : {risk}")

    # ==================================================
    # Original X-ray
    # ==================================================

    c.setFillColor(HexColor("#1565C0"))
    c.setFont("Helvetica-Bold", 15)
    c.drawString(40, height - 335, "Original Chest X-ray")

    if os.path.exists(original_image_path):
        c.drawImage(
            original_image_path,
            60,
            height - 570,
            width=200,
            height=200,
            preserveAspectRatio=True
        )

    # ==================================================
    # Heatmap
    # ==================================================

    c.setFillColor(HexColor("#1565C0"))
    c.setFont("Helvetica-Bold", 15)
    c.drawString(320, height - 335, "Grad-CAM Heatmap")

    if os.path.exists(heatmap_path):
        c.drawImage(
            heatmap_path,
            320,
            height - 570,
            width=200,
            height=200,
            preserveAspectRatio=True
        )

    # ==================================================
    # AI Explanation
    # ==================================================

    c.setFillColor(HexColor("#1565C0"))
    c.setFont("Helvetica-Bold", 15)
    c.drawString(40, 220, "AI Explanation")

    c.setFillColor(HexColor("#000000"))
    c.setFont("Helvetica", 11)

    explanation = [
        f"The AI model predicts {prediction}.",
        f"The confidence score is {confidence}%.",
        "The highlighted Grad-CAM regions indicate",
        "the areas that contributed most to the prediction.",
        "This output is intended to assist clinicians",
        "and should not replace professional diagnosis."
    ]

    y = 200

    for line in explanation:
        c.drawString(50, y, "• " + line)
        y -= 18

    # ==================================================
    # Disclaimer
    # ==================================================

    c.setStrokeColor(HexColor("#BDBDBD"))
    c.line(40, 80, width - 40, 80)

    c.setFillColor(HexColor("#616161"))
    c.setFont("Helvetica-Oblique", 10)

    c.drawCentredString(
        width / 2,
        60,
        "This report is AI-generated and should be reviewed by a qualified radiologist."
    )

    c.drawCentredString(
        width / 2,
        45,
        "© LungAI v1.0"
    )

    c.save()

    return pdf_path